### ISSUE TITLE
Bug likely to do with scraping

### ISSUE THREAD

**Issue by abhinavk99** [sandeepnamburi/PickYourProf#9]
```bash
(node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined
2019-10-24T02:25:48.646449+00:00 app[web.1]:     at Node.<anonymous> (/app/src/algorithm.js:270:44)
2019-10-24T02:25:48.646451+00:00 app[web.1]:     at initialize.exports.each (/app/node_modules/cheerio/lib/api/traversing.js:300:24)
2019-10-24T02:25:48.646453+00:00 app[web.1]:     at fetch.then.then.html (/app/src/algorithm.js:268:17)
2019-10-24T02:25:48.646456+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-24T02:25:48.646517+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by abhinavk99** [comment]
Fixed in v2.3.1, commit f0aebb8afdff706f570919707128ee89003803b9
